
include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - "lib/**/i18n.dart"
  errors:
    todo: ignore

linter:
  rules:
    always_declare_return_types: true
    unnecessary_this: true
    avoid_print: true
    empty_statements: true
    iterable_contains_unrelated_type: true
    literal_only_boolean_expressions: true
    always_specify_types: true
    avoid_as: true
    await_only_futures: true
    empty_catches: true
    file_names: true
    prefer_expression_function_bodies: true
    prefer_single_quotes: true

    # disabling rules
    omit_local_variable_types: false