name: push_app
description: A centralized marketplace for traveling barbers and hair stylists in need of a temporary booth

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  storybook_flutter: ^0.5.0
  flutter_svg: ^0.21.0-nullsafety.0
  faker: ^2.0.0-rc.2
  cloud_firestore: ^1.0.7
  firebase_core: ^1.01.0
  firebase_auth: ^1.1.2
  firebase_storage:  ^8.0.5
  firebase_remote_config: ^0.10.0-dev.2 
  algolia: ^1.0.1
  enum_to_string: ^1.0.13
  image_picker: ^0.7.3
  permission_handler: ^6.1.1
  carousel_slider: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:

  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/images/


  fonts:
    - family: Millik
      fonts:
        - asset: lib/assets/fonts/Millik.ttf
    - family: Gilroy
      fonts:
        - asset: lib/assets/fonts/Gilroy-Black.otf
        - asset: lib/assets/fonts/Gilroy-BlackItalic.otf
          style: italic
        - asset: lib/assets/fonts/Gilroy-Heavy.otf
          weight: 900
        - asset: lib/assets/fonts/Gilroy-HeavyItalic.otf
          weight: 900
          style: italic
        - asset: lib/assets/fonts/Gilroy-ExtraBold.otf
          weight: 800
        - asset: lib/assets/fonts/Gilroy-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/Gilroy-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/Gilroy-BoldItalic.otf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/Gilroy-SemiBold.otf
          weight: 600
        - asset: lib/assets/fonts/Gilroy-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/Gilroy-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/Gilroy-MediumItalic.otf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Gilroy-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/Gilroy-RegularItalic.otf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/Gilroy-Light.otf
          weight: 300
        - asset: lib/assets/fonts/Gilroy-LightItalic.otf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/Gilroy-UltraLight.otf
          weight: 200
        - asset: lib/assets/fonts/Gilroy-UltraLightItalic.otf
          weight: 200
          style: italic
        - asset: lib/assets/fonts/Gilroy-Thin.otf
          weight: 100
        - asset: lib/assets/fonts/Gilroy-ThinItalic.otf
          weight: 100
          style: italic

